### ISSUE TITLE
Multiple CD albums

### ISSUE THREAD

**Issue by naggie** [naggie/crates#18]
Do we combine them into one 'Album'?

I think by the time it's in crates you've lost all concept of a shiny disc anyway.

It would involve a bit of magic -- removing CD number via regex -- which technically should not be in the album title anyway.

**Comment by jimjibone** [comment]
I say combine them into one album. Ditch the CD numbers!

I wouldn't have thought that album downloads contain CD numbers any more, if ever, but iTunes does have a CD number tag.

Keeping CD's separate may make the UX more painful for the user. Searching for "Fast Jungle Music" and being asked if we would like CD 1 or CD 2 would be annoying.

**Comment by naggie** [comment]
Yes -- true. The only thing is song ordering, especially with a continuous mix. However, I don't think I care about that.

I'll combine multiple CDs.

**Comment by naggie** [comment]
Some have different covers per CD. As we match on album/artist first, this shouldn't be a problem most of the time.
