### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by naggie** [naggie/crates#2]
I assume we should use SCSS. Any objections, @jimjibone ?

https://github.com/davidguttman/sassify would work nicely with our browserify flow. Especially as this allows us to `require()` scss files directly -- which makes sense because every react component will rely on an associated style anyway.

**Comment by jimjibone** [comment]
Yes MOAR SCSS! It seems to be the most popular CSS preprocessor on the internet at the moment. Also I have used it many times. 

Hmmm, Sassify looks interesting. I'd be interested to see what the output looks like. So far I have just been using gulp-sass, doing a regular SCSS compile into a single CSS file. Then include this on my webpage as normal. This way works very well for me but if Sassify is better then we should do that. It sounds like Sassify would help with encapsulation of styles, I.e. The shadow dom.

**Comment by naggie** [comment]
Quite right. Sassify does look good but immature and not popular -- the author even warns that it doesn't work with specific versions of node. Fail.

Considering SCSS supports `@import` perhaps the regular SCSS compiler, programatic mode is the answer. Otherwise, gulp if you'd like to hack it in.

**Comment by jimjibone** [comment]
Ahh yes. Fail!

I say just use the gulp-sass module. It supports standard SCSS files. Also I have used `@import` in SCSS, very straightforward to use. Why do hacking?

**Comment by naggie** [comment]
I mean hacking as in committing gulp code loool

**Comment by jimjibone** [comment]
Committing the gulp CSS output? Yeah it is a bit bad having built files committed... Or we could use a browser side SCSS compiler?

**Comment by naggie** [comment]
No, I mean adding a gulp powered SCSS + JS (etc) build script to Crates

**Comment by jimjibone** [comment]
You've lost me haha. How is gulp a hack?

**Comment by jimjibone** [comment]
Also, Angie says happy birthday :)

**Comment by naggie** [comment]
Thanks Ange!

Gulp isn't a hack. I meant hack as in write some code! You need some embarrassingly strong coffee!
1. Write gulp build script
2. SCSS compiler, browerify+reactify
3. ???
4. Hopefully comprehension

**Comment by jimjibone** [comment]
Ahh ok I see. Hahaha I think we just define hacking differently.

3 . Inject magic smoke

Would you be ok with committing the compiled output from the gulp script? Obviously only commit working code. This way a user/ansible wouldn't have to install npm etc as well as Crates/Python. Or do you think the extra step is ok?

**Comment by naggie** [comment]
I think the extra step us fine until we find otherwise. The ansible based deploy, which may be our only supported deploy method deals with it automatically.

Magic smoke -- almost forgot!

**Comment by naggie** [comment]
Oh we have this. Gulp later.
