### ISSUE TITLE
Flux implementation

### ISSUE THREAD

**Issue by naggie** [naggie/crates#20]
We could use vanilla (facebook example dispatch, node eventemitter store etc) but I'd like to check out nuclearJS http://optimizely.github.io/nuclear-js/

as recommended by balloob who uses it for home-assistant.

**Comment by naggie** [comment]
Still looking, so many. Flux, redux, fluxxor,  marty.js blah blah blah.

**Comment by naggie** [comment]
http://alt.js.org/ chosen so far. Could use TimeTravelStore to implement undo/history

**Comment by naggie** [comment]
http://jamesknelson.com/which-flux-implementation-should-i-use-with-react/

Some have bowed out. Now it's between Redux, Alt.js and a flux-like custom job. FB Flux is more of a learning tool IMO.

Redux now exists in the official reactjs account. That means something.

---

For async, use react-think which allows actions to be "thunks" which are just functions that defer..

Use ES6 Object.assign() to create a new modified copy, or the proposed spread (`...`) operator.

---

May consider also using Deku instead of react as all Deku views are purely functional and therefore can't have state; possible with react but forced with Deku....?

**Comment by naggie** [comment]
Infinite scroll requires state during async call -- page number. This can be passed by a component to the (async) action, but this feels wrong. The solution, according to redux-thunk, is to take the second param of the callback return which is a method to get the current state.

![image](https://cloud.githubusercontent.com/assets/208440/14315798/53ade9b2-fbf7-11e5-8663-361e773d3ddd.png)

**Comment by naggie** [comment]
MOAR REDUX
![image](https://cloud.githubusercontent.com/assets/208440/14334977/d52b3fb4-fc4f-11e5-89b2-482b015efd09.png)

**Comment by naggie** [comment]
Redux is now in master and powering the browser. Player + album view to come.

**Comment by naggie** [comment]
@jimjibone at last!

**Comment by jimjibone** [comment]
YEAH!
